name: Treeumph Deploy

on:
  push:
    branches: ['main']

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      - SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
      - SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - MORE_TREES_API_KEY: ${{ secrets.MORE_TREES_API_KEY }}
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: rome/setup-rome@v0.4
        with:
          version: latest
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - run: rome ci .
      - name: Setup AWS creds
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1
      - name: Deploy to AWS
        uses: serverless/github-action@v3.1
        with:
          args: deploy
        env:
          SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          MORE_TREES_API_KEY: ${{ secrets.MORE_TREES_API_KEY }}

